// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Philson.Models;

namespace Philson.Migrations
{
    [DbContext(typeof(PhilsonContext))]
    [Migration("20190714014437_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Philson.Models.SuppliedInterloan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barcode");

                    b.Property<string>("CallNo");

                    b.Property<string>("FurtherDetails");

                    b.Property<string>("Handler");

                    b.Property<string>("ILLRequestNo");

                    b.Property<string>("ItemType");

                    b.Property<DateTime>("RequestDate");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<string>("StaffRequesting");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("SuppliedInterloan");
                });
#pragma warning restore 612, 618
        }
    }
}
